name: updates-log

services:
  appserver:
    type: php:7.4
    webroot: drupal/web
    build_as_root:
      - /app/.lando/build_as_root
    build:
      - /app/.lando/build
    run_as_root:
      - /app/.lando/run_as_root
    run:
      - /app/.lando/run
  mariadb:
    type: mariadb:10.6

tooling:
  install:
    service: appserver
    cmd: /app/.lando/cmd-install
  test:
    service: appserver
    cmd: /app/.lando/cmd-test
  scan:
    service: appserver
    cmd: /app/.lando/cmd-scan

version: 3.6.2
